/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.security.CodeSource;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.filechooser.FileNameExtensionFilter;
//import org.jcp.xml.dsig.internal.dom.Utils;

/**
 *
 * @author diego
 */
public class Ventana1 extends javax.swing.JFrame {
    DefaultListModel model = new DefaultListModel();
    DefaultListModel model1 = new DefaultListModel();
    Component temp;
    int ind;
    String psw;
    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        
        // <editor-fold defaultstate="collapsed" desc="Proceso para leer archivo pwd (contraseña)">
        //CodeSource codeSource = funcionesUtilidad.class.getProtectionDomain().getCodeSource();
        //new File(codeSource.getLocation().toURI().getPath());
        //File jarFile = new File(Utils.class.getResource("/pwd").getFile());
        //File jarDir = jarFile.getParentFile();
        //JOptionPane.showMessageDialog(null, jarFile);
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
 
        try {
        // 1 Apertura del fichero y creacion de BufferedReader para poder
        //   hacer una lectura comoda (disponer del metodo readLine()).
            
            //String curDir = System.getProperty("/");
            //JOptionPane.showMessageDialog(null, curDir);
        
        archivo = new File ("/home/diego/Escritorio/pwd"); //"/home/diego/Escritorio/pwd"
        fr = new FileReader (archivo);
        br = new BufferedReader(fr);

        // 2 Lectura del fichero
        String linea=br.readLine();
            if(linea!=null) {
                psw=linea;
            }else{
                JOptionPane.showMessageDialog(null, "archivo no contiene la contraseña");
            }
            
        }
        catch(Exception e){
                
        }
        finally{
        // 3 En el finally cerramos el fichero, para asegurarnos
        //   que se cierra tanto si todo va bien como si salta 
        //   una excepcion.
            try{                    
                if( null != fr ){   
                    fr.close();     
                    }
            }
            catch (Exception e2){ 
                
            }
        }
        //</editor-fold>
        
        ind= 0; // indice siempre inicia en 0
        temp=jTabbedPane1.getComponentAt(ind); //guarda temporalmente lo q esta en el index ind del jtabbed panel
        jTabbedPane1.removeTabAt(ind); //"esconder el jpanel1
        jButton4.setVisible(false); // boton devolver
        jLabel2.setVisible(false);  // label informativo del path donde se encuentra el archivo cargado en jpanel1
        jLabel5.setVisible(false);  // label informativo de la ubicación donde se encuentra el archivo cargado en jpanel2
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(247, 246, 246));
        jPanel1.setEnabled(false);
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jpanel1focusjtextfield(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jScrollPane1.setViewportView(jList1);

        jTextField1.setText("Digite el código aquí");
        jTextField1.setEnabled(false);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jText1(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IngEnter(evt);
            }
        });

        jButton1.setText("Registrar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Cargar ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Guardar");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ticket (Unidad)");

        jLabel2.setText("</ubicación/nombrearchivo.xls>");
        jLabel2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(267, 267, 267)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tickets", jPanel1);

        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                vvv(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jButton3.setText("Registrar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regEnter(evt);
            }
        });

        jTextField2.setText("Digite el código aquí");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busEnter(evt);
            }
        });

        jButton4.setText("Volver");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Buscar");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Sin registrar");

        jLabel4.setText("Registrados");

        jLabel5.setText("</ubicacion/nombrearchivo.xls>");

        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList3.setEnabled(false);
        jScrollPane3.setViewportView(jList3);

        jButton8.setText("Cargar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5))
                                    .addComponent(jButton8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))))
                    .addComponent(jLabel3)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addGap(0, 192, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton8))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addGap(0, 52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar", jPanel2);

        jTabbedPane1.setSelectedIndex(1);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/banner.gif"))); // NOI18N

        jPanel3.setBackground(java.awt.Color.black);
        jPanel3.setForeground(java.awt.Color.black);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/gpslogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jMenu1.setText("Menú");

        jMenu3.setText("Administrador");

        jMenuItem2.setText("Ingresar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Cambiar contraseña");
        jMenuItem3.setEnabled(false);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenuItem1.setText("Usuario");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // ingresar - ticket
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        if (evt.getSource().equals(jButton1)) {
            if (! jTextField1.getText().trim().equals("")) {
                if (!jTextField1.getText().trim().equals("Digite el código aquí")) {
                    
                    //comprobar q el ticket no se encuentra en la lista
                    
                    int size = model.getSize();
                    // comprobar si el elemento a ingresar ya esta en la lista de regristrados
                    
                    int size1 = model1.getSize();
                    String texto = jTextField1.getText();
                    boolean sw1=false;
                    for (int i = 0; i < size1; i++) {
                        String textol = model1.getElementAt(i).toString();
                        if ( textol.equals(texto)) {                    
                            jList2.setSelectedIndex(i);
                            sw1=true;
                        }

                    }      
                    if (sw1==true) {
                            JOptionPane.showMessageDialog(null, "Código ya esta registrado");
                    }else{
                    
                    
                        if (size==0) { //si lista vacía entonces ingrese

                            model.addElement(jTextField1.getText());
                            this.jList1.setModel(model);
                            this.jList3.setModel(model);

                            jButton2.setEnabled(true);
                            jButton7.setEnabled(true);
                        } else { //si no comprobar q el ticket no se encuentre en la lista misma

                            boolean sw = false;

                            for (int i = 0; i < size; i++) { // recorro la lista buscando el elemento
                                String textol = model.getElementAt(i).toString();
                                if ( textol.equals(jTextField1.getText())) {
                                    sw=true;    // encontrado
                                }
                            }
                            if (sw==true) { 
                                JOptionPane.showMessageDialog(null, "Código repetido");

                            } else {    // si no encontrado agregarlo
                                model.addElement(jTextField1.getText());
                                this.jList1.setModel(model);
                                this.jList3.setModel(model);

                                jButton2.setEnabled(true);
                                jButton7.setEnabled(true);
                            }
                        }
                    }
                    
                    
                    jTextField1.setText(null);
                    
                    this.jTextField1.requestFocus();
                    
                    
                    }else{
                        jTextField1.setText(null);
                        this.jTextField1.requestFocus();
                    }
                }else{
                    jTextField1.setText(null);
                    this.jTextField1.requestFocus();
                }
            }  
    }//GEN-LAST:event_jButton1ActionPerformed
    // dialogo cargar 
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        FileReader fr = null;
        BufferedReader br = null;
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
        
        if (resultado == JFileChooser.CANCEL_OPTION) {
            return;
        } else {
            File archivo=fileChooser.getSelectedFile();
            
            
            try {
                fr = new FileReader (archivo);
                br = new BufferedReader(fr);
                
                String linea;
                while((linea=br.readLine())!=null){
                    
                    model.addElement(linea);
                    
                }
                jList1.setModel(model);
                jList3.setModel(model);
            } catch (Exception ex) {
            }
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    // Guardar 
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        String suffix=".csv";
        JFileChooser fileChooser = new JFileChooser();
        
        FileNameExtensionFilter filtroImagen=new FileNameExtensionFilter("csv","csv");
        fileChooser.setFileFilter(filtroImagen);
        
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado = fileChooser.showSaveDialog(this);
        
        if (resultado == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File archivo = fileChooser.getSelectedFile();
        
        if(!fileChooser.getSelectedFile().getAbsolutePath().endsWith(suffix)){
            archivo = new File(fileChooser.getSelectedFile() + suffix);
            }
        try {
            int size = model.getSize();
            for (int i = 0; i < size; i++) {                
                jList3.setSelectedIndex(i);
                BufferedWriter out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(archivo, true), "UTF8"));

                out.write(model.getElementAt(i).toString());
                out.write("\n");
                out.close();
            } 
         } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed
    //      Para mantener el jtextfield1 limpio cada vez q se enfoque
    private void jText1(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jText1
        // TODO add your handling code here:
        jTextField1.setText(null);
        jButton1.setEnabled(true);
        
    }//GEN-LAST:event_jText1
    // eliminar - ticket
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        if (jList1.getSelectedValue()!=null) {
            
            int a = jList1.getSelectedIndex();
            model.remove(a);
            int size = model.getSize();
            if (size == 0) { 
                jButton2.setEnabled(false);
                jButton7.setEnabled(false);
            }else{
                if (a == model.getSize()) {
                    //removed item in last position
                    a--;
                }

                jList1.setSelectedIndex(a);
                jList1.ensureIndexIsVisible(a);
                jList3.setSelectedIndex(a);
                jList3.ensureIndexIsVisible(a);
            }
        } else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un ticket para eliminar");
        }       
        
    }//GEN-LAST:event_jButton2ActionPerformed
    //      para mantener el jtextfield2 limpio cada vez q se enfoque
    private void jTextField2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2
        // TODO add your handling code here:
        
        jTextField2.setText(null);
        jButton5.setEnabled(true);
        jButton3.setEnabled(false);
        
    }//GEN-LAST:event_jTextField2
    // buscar
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
        
        if (!jTextField2.getText().trim().equals("")) {
            int size = model.getSize();
            String texto = jTextField2.getText();
            boolean sw=false;
            for (int i = 0; i < size; i++) {
                String textol = model.getElementAt(i).toString();
                if ( textol.equals(texto)) {                    
                    jList3.setSelectedIndex(i);
                    jButton3.setEnabled(true);
                    sw=true;
                    jButton3.requestFocus();
                }
                
            }      
            if (sw==false) {
                    JOptionPane.showMessageDialog(null, "Código no encontrado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Digite un código a buscar");
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed
    // registrar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if (!jTextField2.getText().trim().equals("")) {
            
            
            
            model1.addElement(jTextField2.getText());
            jList2.setModel(model1);

            int a = jList3.getSelectedIndex();
            model.remove(a);
            jButton3.setEnabled(false);
            
            
        }
        jTextField2.setText(null);
        jButton4.setEnabled(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed
    // devolver 
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        int a = jList2.getSelectedIndex();
        if (a==-1) {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento para devolver");
        } else {
        }
        model.addElement(model1.getElementAt(a));
        jList3.setModel(model);
        
        model1.remove(a);
        jButton4.setEnabled(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed
    //      habilita boton devolver - setenable(true)
    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // TODO add your handling code here:
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jList2ValueChanged
    // Enter - jtextfield1 ingresar
    private void IngEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngEnter
        // TODO add your handling code here:
        
        
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           
            // ingresar - ticket
            if (! jTextField1.getText().trim().equals("")) {
                if (!jTextField1.getText().trim().equals("Digite el código aquí")) {
                    //comprobar q el ticket no se encuentra en la lista
                    int size = model.getSize();
                    if (size==0) { //si lista vacía entonces ingrese
                        
                        model.addElement(jTextField1.getText());
                        this.jList1.setModel(model);
                        this.jList3.setModel(model);
                        
                        jButton2.setEnabled(true);
                        jButton7.setEnabled(true);
                    } else { //si no comprobar q el ticket no se encuentre en la lista
                        
                        boolean sw = false;
                        
                        for (int i = 0; i < size; i++) { // recorro la lista buscando el elemento
                            String textol = model.getElementAt(i).toString();
                            if ( textol.equals(jTextField1.getText())) {
                                sw=true;    // encontrado
                            }
                        }
                        if (sw==true) { // enviar mensaje de repetido
                            JOptionPane.showMessageDialog(null, "Código repetido");
                            
                        } else {    // si no encontrado agregarlo
                            model.addElement(jTextField1.getText());
                            this.jList1.setModel(model);
                            this.jList3.setModel(model);

                            jButton2.setEnabled(true);   
                            jButton7.setEnabled(true);
                        }
                    }
                    
                    jTextField1.setText(null);                    
                    this.jTextField1.requestFocus();                    
                    }else{
                        jTextField1.setText(null);
                        this.jTextField1.requestFocus();
                    }
                }else{
                    jTextField1.setText(null);
                    this.jTextField1.requestFocus();
                }
            
            
        }
        
    }//GEN-LAST:event_IngEnter
    // enter - buscar
    private void busEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busEnter
        // TODO add your handling code here:
        
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (!jTextField2.getText().trim().equals("")) {
                int size = model.getSize();
                String texto = jTextField2.getText();
                boolean sw = false;    
                for (int i = 0; i < size; i++) {
                    String textol = model.getElementAt(i).toString();
                    if ( textol.equals(texto)) {
                        jList3.setSelectedIndex(i);
                        jButton3.setEnabled(true);
                        jButton3.requestFocus();              
                        sw=true;
                    }
                } 
                if (sw==false) {
                    JOptionPane.showMessageDialog(null, "Código no encontrado");
                }
                
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Digite un código a buscar");
            }
        }
    }//GEN-LAST:event_busEnter
    //      para enfocar en jtextfield2 cada vez que se da enter
    private void regEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regEnter
        // TODO add your handling code here:        
        jTextField2.requestFocus();
    }//GEN-LAST:event_regEnter
    //      para cada vez que se abre el jpanel2 mantener enfocado en el jtextfield2
    private void vvv(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_vvv
        // TODO add your handling code here:
        jTextField2.requestFocus();
    }//GEN-LAST:event_vvv
    //      para cada vez que se abre el jpanel1 mantener enfocado en el jtextfield1
    private void jpanel1focusjtextfield(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jpanel1focusjtextfield
        // TODO add your handling code here:
        jTextField1.requestFocus();
    }//GEN-LAST:event_jpanel1focusjtextfield
    // ingresar como admin
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        JPasswordField pwd = new JPasswordField(10);  
        int action = JOptionPane.showConfirmDialog(null, pwd,"Ingrese Contraseña",JOptionPane.OK_CANCEL_OPTION); 
        if (action==0) {
            String contr = new String(pwd.getPassword());
            if (contr == null ? psw == null : contr.equals(psw)) { //validando contraseña
                jTextField1.setEnabled(true);
                jTabbedPane1.add("Tickets", temp); // se adiciona el panel tickets        
                jMenuItem1.setEnabled(true);
                jButton4.setVisible(true);
                jMenuItem3.setEnabled(true);
                jTabbedPane1.setSelectedIndex(1);
                jMenuItem2.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(null, "Contraseña errada");
            }
        } 
            
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    // ingresar como user
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jMenuItem3.setEnabled(false);   // menu admin-cambiar contraseña
        jButton4.setVisible(false);     // boton volver
        jMenuItem2.setEnabled(true);    // menu admin-ingresar
        jMenuItem1.setEnabled(false);   // menu usuario
        
        ind= jTabbedPane1.getSelectedIndex();
        
        if (jTabbedPane1.getComponentAt(ind)==temp) {
            jTabbedPane1.removeTabAt(ind);
        } else {
            if (ind==0) {
                ind=ind+1;
                temp=jTabbedPane1.getComponentAt(ind);
                jTabbedPane1.removeTabAt(ind); // se elimina el panel q no debe ver el usuario
                
            } else {
                temp=jTabbedPane1.getComponentAt(ind);
                jTabbedPane1.removeTabAt(ind); // se elimina el panel q no debe ver el usuario
                
            }            
        }
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    // Cambio de contraseña // falta colocar campo contraseñas ********
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         
         String contr = JOptionPane.showInputDialog("Ingrese contraseña vieja"); // colocar campo contraseñas
         String contr2 = JOptionPane.showInputDialog("Ingrese contraseña vieja otra vez"); // colocar campo contraseñas
         
         if (contr == null ? contr2 == null : contr.equals(contr2)&& (psw == null ? contr == null : psw.equals(contr)) ) {
            String contr3 = JOptionPane.showInputDialog("Ingrese contraseña nueva"); // colocar campo contraseñas
            String contr4 = JOptionPane.showInputDialog("Ingrese contraseña nueva otra vez"); // colocar campo contraseñas
            if (contr3 == null ? contr4 == null : contr3.equals(contr4)) {
                psw=contr4; // Actualiza la variable global de la contraseña
                 
                FileWriter fichero = null;
                PrintWriter pw = null;
                try
                {
                    fichero = new FileWriter("/home/diego/Escritorio/pwd");
                    pw = new PrintWriter(fichero);
                    
                    pw.println(contr4); // escribe nuevo archivo pwd con nueva contraseña

                } catch (Exception e) {
                    
                } finally {
                   try {
                   // Nuevamente aprovechamos el finally para 
                   // asegurarnos que se cierra el fichero.
                        if (null != fichero) {
                           fichero.close();
                        }
                   } 
                   catch (Exception e2) {
                      
                   }
                }
                 
                 JOptionPane.showMessageDialog(null,"Contraseña agregada correctamente");
             } else {
                 JOptionPane.showMessageDialog(null,"No coinciden las contraseñas nueva");
             }
        } else {
             JOptionPane.showMessageDialog(null,"Contraseña errada o no coinciden las contraseñas ");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        FileReader fr = null;
        BufferedReader br = null;
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
        
        if (resultado == JFileChooser.CANCEL_OPTION) {
            return;
        } else {
            File archivo=fileChooser.getSelectedFile();
            
            
            try {
                fr = new FileReader (archivo);
                br = new BufferedReader(fr);
                
                String linea;
                while((linea=br.readLine())!=null){
                    
                    model.addElement(linea);
                    
                }
                jList1.setModel(model);
                jList3.setModel(model);
            } catch (Exception ex) {
            }
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
